version: '3.6'
services:
  api:
    build: ./api
    container_name: api
    depends_on:
      - postgres
    env_file: .env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:$POSTGRES_PASSWORD@postgres:5432/postgres
    expose:
      - 8000
    restart: always

  postgres:
    container_name: postgres
    env_file: .env
    ports:
      - 5432:5432
    image: postgres:12-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro

  hasura:
    container_name: hasura
    depends_on:
      - postgres
    env_file: .env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:$POSTGRES_PASSWORD@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "${HASURA_GRAPHQL_JWT_KEY}"}'
    image: hasura/graphql-engine:v1.2.0-beta.5.cli-migrations-v2
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata

  frontend:
    build: ./client
    container_name: frontend
    expose:
      - 80
    restart: always

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/config:/etc/nginx/conf.d:ro

volumes:
  postgres:
